apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: frybot

images:
  - name: ghcr.io/tebriel/fry-bot
    digest: sha256:bfb2e08193c395327fe06afbebe425a9576afa1b12a4a2b6d80fdcfdbcb18c04

resources:
- fry-bot.yaml

secretGenerator:
- name: fry-bot-env
  envs:
  - .env
