kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfsdata-runstator
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: nfsdata-runstator
  storageClassName: azureblobfuse-standard
