kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfsdata-runtator
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: nfsdata-runtator
  storageClassName: azureblob-nfs-premium
