apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfsdata-web
  labels:
    type: nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # If set as "Delete" container would be removed after pvc deletion
  storageClassName: azureblob-nfs-premium
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    # make sure volumeid is unique for every identical storage blob container in the cluster
    # character `#` is reserved for internal use and cannot be used in volumehandle
    volumeHandle: takahe-web
    volumeAttributes:
      resourceGroup: takahe.pindropt.fail
      storageAccount: takahepindropt
      containerName: media
      protocol: nfs
